"use client";

import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { approveRun, fetchPendingApprovals, rejectRun } from "@/lib/api";
import type { ApprovalRecord } from "@/lib/types";

const RISK_COLOR: Record<string, string> = { low: "bg-gray-100 text-gray-600", medium: "bg-amber-100 text-amber-700", high: "bg-orange-100 text-orange-700", critical: "bg-red-100 text-red-700" };

function ApprovalCard({ record, onApprove, onReject, loading }: { record: ApprovalRecord; onApprove: (id: string) => void; onReject: (id: string) => void; loading: boolean }) {
  const [expanded, setExpanded] = useState(false);
  return <div className="bg-white rounded-xl border border-gray-200 shadow-sm p-5 space-y-3"><div className="flex items-start justify-between gap-3"><div className="space-y-0.5"><div className="flex items-center gap-2"><span className="text-xs font-bold text-gray-500 bg-gray-100 px-2 py-0.5 rounded">{record.task_id}</span><span className={`text-xs font-semibold px-2 py-0.5 rounded ${RISK_COLOR[record.risk_level] ?? RISK_COLOR.medium}`}>{"\uc704\ud5d8\ub3c4 "}{record.risk_level}</span></div><p className="text-sm font-medium text-gray-900 mt-1">{record.summary}</p><p className="text-xs text-gray-400">{"\uc694\uccad \uc2dc\uac01: "}{new Date(record.requested_at).toLocaleString("ko-KR")}</p></div><div className="flex gap-2 flex-shrink-0"><button onClick={() => onApprove(record.approval_id)} disabled={loading} className="px-3 py-1.5 text-xs font-semibold rounded-lg bg-emerald-600 text-white hover:bg-emerald-700 disabled:opacity-50">{"\uc2b9\uc778"}</button><button onClick={() => onReject(record.approval_id)} disabled={loading} className="px-3 py-1.5 text-xs font-semibold rounded-lg bg-red-100 text-red-700 hover:bg-red-200 disabled:opacity-50">{"\uac70\uc808"}</button></div></div><button onClick={() => setExpanded((v) => !v)} className="text-xs text-blue-500 hover:underline">{expanded ? "\ubbf8\ub9ac\ubcf4\uae30 \ub2eb\uae30" : "\uc2e4\ud589 \ubbf8\ub9ac\ubcf4\uae30"}</button>{expanded && <pre className="text-xs bg-gray-50 border border-gray-100 rounded-lg p-3 overflow-auto max-h-48 text-gray-700">{JSON.stringify(record.preview, null, 2)}</pre>}<p className="text-[10px] text-gray-400 font-mono">approval_id: {record.approval_id} / trace_id: {record.trace_id}</p></div>;
}

export default function ApprovalsPage() {
  const queryClient = useQueryClient();
  const { data: records = [], isLoading, isError, refetch } = useQuery({ queryKey: ["approvals", "pending"], queryFn: fetchPendingApprovals, refetchInterval: 5000 });
  const [actionId, setActionId] = useState<string | null>(null);
  const [toast, setToast] = useState<{ msg: string; ok: boolean } | null>(null);
  const showToast = (msg: string, ok: boolean) => { setToast({ msg, ok }); setTimeout(() => setToast(null), 3000); };
  const approveMut = useMutation({ mutationFn: (id: string) => approveRun(id), onMutate: (id) => setActionId(id), onSuccess: (_, id) => { showToast(`\uc2b9\uc778 \uc644\ub8cc (${id})`, true); queryClient.invalidateQueries({ queryKey: ["approvals"] }); queryClient.invalidateQueries({ queryKey: ["runs"] }); }, onError: (err) => showToast(`\uc2b9\uc778 \uc2e4\ud328: ${(err as Error).message}`, false), onSettled: () => setActionId(null) });
  const rejectMut = useMutation({ mutationFn: (id: string) => rejectRun(id), onMutate: (id) => setActionId(id), onSuccess: (_, id) => { showToast(`\uac70\uc808 \uc644\ub8cc (${id})`, true); queryClient.invalidateQueries({ queryKey: ["approvals"] }); }, onError: (err) => showToast(`\uac70\uc808 \uc2e4\ud328: ${(err as Error).message}`, false), onSettled: () => setActionId(null) });
  return <div className="space-y-6 max-w-3xl">{toast && <div className={`fixed bottom-6 right-6 z-50 px-4 py-3 rounded-xl text-sm font-semibold shadow-lg ${toast.ok ? "bg-emerald-600 text-white" : "bg-red-600 text-white"}`}>{toast.msg}</div>}<div className="flex items-center justify-between"><div><h2 className="text-xl font-bold text-gray-900">{"\uc2b9\uc778 \ub300\uae30"}</h2><p className="text-sm text-gray-400 mt-0.5">{"\uace0\uc704\ud5d8 \uc791\uc5c5\uc740 \uc2e4\ud589 \uc804\uc5d0 \uc2b9\uc778\uc774 \ud544\uc694\ud569\ub2c8\ub2e4."}</p></div><button onClick={() => refetch()} className="text-xs text-gray-400 hover:text-gray-600 border border-gray-200 px-3 py-1.5 rounded-lg">{"\uc0c8\ub85c\uace0\uce68"}</button></div><div className="flex items-center gap-2"><span className={`text-xs font-semibold px-2.5 py-1 rounded-full ${records.length > 0 ? "bg-amber-100 text-amber-700" : "bg-gray-100 text-gray-500"}`}>{records.length}{"\uac74 \ub300\uae30 \uc911"}</span><span className="text-xs text-gray-400">{"5\ucd08\ub9c8\ub2e4 \uc790\ub3d9 \uac31\uc2e0"}</span></div>{isLoading ? <div className="space-y-3">{Array.from({ length: 3 }).map((_, i) => <div key={i} className="h-28 bg-gray-100 rounded-xl animate-pulse" />)}</div> : isError ? <div className="py-12 text-center text-sm text-red-500 bg-red-50 rounded-xl border border-red-100">{"Python API(localhost:8001)\uc640 \uc5f0\uacb0\ud560 \uc218 \uc5c6\uc2b5\ub2c8\ub2e4."}</div> : records.length === 0 ? <div className="py-16 text-center text-sm text-gray-400 bg-gray-50 rounded-xl border border-gray-100">{"\ub300\uae30 \uc911\uc778 \uc2b9\uc778 \uc694\uccad\uc774 \uc5c6\uc2b5\ub2c8\ub2e4."}</div> : <div className="space-y-4">{records.map((rec) => <ApprovalCard key={rec.approval_id} record={rec} loading={actionId === rec.approval_id} onApprove={(id) => approveMut.mutate(id)} onReject={(id) => rejectMut.mutate(id)} />)}</div>}</div>;
}
