create table if not exists public.b2_clip_reports_test (
  id bigint generated by default as identity primary key,
  video_url text,
  uploaded_at date,
  channel_name text,
  view_count bigint not null default 0,
  checked_at date not null default current_date,
  clip_title text,
  work_title text,
  platform text,
  rights_holder_name text,
  identifier text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists b2_clip_reports_test_checked_at_idx
  on public.b2_clip_reports_test (checked_at desc);

create index if not exists b2_clip_reports_test_rights_holder_idx
  on public.b2_clip_reports_test (rights_holder_name, checked_at desc);

create index if not exists b2_clip_reports_test_identifier_idx
  on public.b2_clip_reports_test (identifier, checked_at desc);

insert into public.b2_content_catalog (
  content_name,
  identifier,
  rights_holder_name,
  active_flag
)
select
  '현상수배',
  '1UBvb',
  '이놀미디어',
  'Active'
where not exists (
  select 1
  from public.b2_content_catalog
  where content_name = '현상수배'
);

update public.b2_content_catalog
set
  identifier = '1UBvb',
  rights_holder_name = '이놀미디어',
  active_flag = coalesce(active_flag, 'Active')
where content_name = '현상수배';

insert into public.b2_rights_holders (
  rights_holder_name,
  email,
  current_work_title,
  naver_report_enabled,
  update_cycle
)
select
  '이놀미디어',
  'kirby.lee@laeebly.com',
  '현상수배',
  true,
  'daily 10:00 KST'
where not exists (
  select 1
  from public.b2_rights_holders
  where rights_holder_name = '이놀미디어'
);

update public.b2_rights_holders
set
  email = coalesce(email, 'kirby.lee@laeebly.com'),
  current_work_title = coalesce(current_work_title, '현상수배'),
  naver_report_enabled = true,
  update_cycle = coalesce(update_cycle, 'daily 10:00 KST')
where rights_holder_name = '이놀미디어';
