create table if not exists public.b2_clip_report_runs (
  run_id uuid primary key default gen_random_uuid(),
  checked_at timestamptz not null default now(),
  finished_at timestamptz,
  status text not null default 'running'
    check (status in ('running', 'success', 'failed')),
  triggered_by text not null default 'manual'
    check (triggered_by in ('manual', 'schedule', 'api')),
  target_identifier_count integer not null default 0,
  row_count integer not null default 0,
  error_message text,
  created_at timestamptz not null default now()
);

create index if not exists b2_clip_report_runs_checked_at_idx
  on public.b2_clip_report_runs (checked_at desc);

create index if not exists b2_clip_report_runs_status_checked_idx
  on public.b2_clip_report_runs (status, checked_at desc);

create table if not exists public.b2_clip_reports_daily (
  id bigint generated by default as identity primary key,
  run_id uuid not null references public.b2_clip_report_runs(run_id) on delete cascade,
  video_url text,
  uploaded_at date,
  channel_name text,
  view_count bigint not null default 0,
  checked_at timestamptz not null,
  clip_title text,
  work_title text,
  platform text not null default 'naver_clip',
  rights_holder_name text,
  identifier text,
  content_catalog_id bigint,
  rights_holder_id bigint,
  created_at timestamptz not null default now()
);

create unique index if not exists b2_clip_reports_daily_run_video_uidx
  on public.b2_clip_reports_daily (run_id, video_url)
  where video_url is not null and video_url <> '';

create index if not exists b2_clip_reports_daily_checked_at_idx
  on public.b2_clip_reports_daily (checked_at desc);

create index if not exists b2_clip_reports_daily_holder_checked_idx
  on public.b2_clip_reports_daily (rights_holder_name, checked_at desc);

create index if not exists b2_clip_reports_daily_work_checked_idx
  on public.b2_clip_reports_daily (work_title, checked_at desc);

create index if not exists b2_clip_reports_daily_identifier_checked_idx
  on public.b2_clip_reports_daily (identifier, checked_at desc);

create table if not exists public.b2_clip_reports_year (
  year integer not null,
  rights_holder_name text not null,
  work_title text not null,
  identifier text not null,
  clip_count bigint not null default 0,
  total_views bigint not null default 0,
  max_view_count bigint not null default 0,
  first_checked_at timestamptz,
  latest_checked_at timestamptz,
  updated_at timestamptz not null default now(),
  primary key (year, rights_holder_name, work_title, identifier)
);

create index if not exists b2_clip_reports_year_holder_year_idx
  on public.b2_clip_reports_year (rights_holder_name, year desc);

create or replace function public.refresh_b2_clip_reports_year(target_year integer)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  delete from public.b2_clip_reports_year
  where year = target_year;

  insert into public.b2_clip_reports_year (
    year,
    rights_holder_name,
    work_title,
    identifier,
    clip_count,
    total_views,
    max_view_count,
    first_checked_at,
    latest_checked_at,
    updated_at
  )
  select
    extract(year from checked_at at time zone 'Asia/Seoul')::integer as year,
    coalesce(rights_holder_name, '') as rights_holder_name,
    coalesce(work_title, '') as work_title,
    coalesce(identifier, '') as identifier,
    count(*) as clip_count,
    sum(view_count) as total_views,
    max(view_count) as max_view_count,
    min(checked_at) as first_checked_at,
    max(checked_at) as latest_checked_at,
    now() as updated_at
  from public.b2_clip_reports_daily
  where extract(year from checked_at at time zone 'Asia/Seoul')::integer = target_year
  group by
    extract(year from checked_at at time zone 'Asia/Seoul')::integer,
    coalesce(rights_holder_name, ''),
    coalesce(work_title, ''),
    coalesce(identifier, '');
end;
$$;

create or replace view public.v_b2_clip_reports_daily_latest as
select d.*
from public.b2_clip_reports_daily d
join (
  select run_id
  from public.b2_clip_report_runs
  where status = 'success'
  order by checked_at desc
  limit 1
) latest on latest.run_id = d.run_id;

create or replace view public.v_b2_clip_reports_daily_history as
select
  d.*,
  r.status as run_status,
  r.triggered_by,
  r.finished_at,
  extract(year from d.checked_at at time zone 'Asia/Seoul')::integer as checked_year,
  (d.checked_at at time zone 'Asia/Seoul')::date as checked_date_kst
from public.b2_clip_reports_daily d
join public.b2_clip_report_runs r on r.run_id = d.run_id;

with new_run as (
  insert into public.b2_clip_report_runs (
    checked_at,
    finished_at,
    status,
    triggered_by,
    target_identifier_count,
    row_count
  )
  select
    timestamp '2026-04-30 10:00:00' at time zone 'Asia/Seoul',
    now(),
    'success',
    'manual',
    count(distinct identifier),
    count(*)
  from public.b2_clip_reports_test
  where checked_at = date '2026-04-30'
  having count(*) > 0
  returning run_id, checked_at
),
deduped_test_rows as (
  select *
  from (
    select
      t.*,
      row_number() over (
        partition by t.video_url
        order by t.view_count desc nulls last, t.uploaded_at desc nulls last, t.id desc
      ) as rn
    from public.b2_clip_reports_test t
    where t.checked_at = date '2026-04-30'
      and t.video_url is not null
      and t.video_url <> ''
  ) ranked
  where rn = 1
)
insert into public.b2_clip_reports_daily (
  run_id,
  video_url,
  uploaded_at,
  channel_name,
  view_count,
  checked_at,
  clip_title,
  work_title,
  platform,
  rights_holder_name,
  identifier
)
select
  new_run.run_id,
  t.video_url,
  t.uploaded_at,
  t.channel_name,
  t.view_count,
  new_run.checked_at,
  t.clip_title,
  t.work_title,
  coalesce(t.platform, 'naver_clip'),
  t.rights_holder_name,
  t.identifier
from deduped_test_rows t
cross join new_run
on conflict (run_id, video_url) where video_url is not null and video_url <> '' do nothing;

select public.refresh_b2_clip_reports_year(2026);
