begin;

alter table if exists public.profiles rename to user_profiles;
alter table if exists public.channel_approvals rename to creator_channel_applications;
alter table if exists public.work_requests rename to work_usage_requests;
alter table if exists public.channel_stats rename to creator_channel_monthly_stats;
alter table if exists public.leads rename to lead_channels;
alter table if exists public.email_logs rename to lead_email_deliveries;
alter table if exists public.integration_runs rename to automation_runs;
alter table if exists public.agent_traces rename to automation_agent_traces;
alter table if exists public.agent_approvals rename to automation_approvals;
alter table if exists public.agent_tool_invocations rename to automation_tool_invocations;

alter table if exists public.b2_content_catalog rename to naver_works;
alter table if exists public.b2_rights_holders rename to naver_rights_holders;
alter table if exists public.b2_clip_reports rename to naver_clip_report_legacy_rows;
alter table if exists public.b2_clip_reports_test rename to naver_clip_report_staging;
alter table if exists public.b2_clip_report_runs rename to naver_clip_report_runs;
alter table if exists public.b2_clip_reports_daily rename to naver_clip_report_daily_rows;
alter table if exists public.b2_clip_reports_year rename to naver_clip_report_yearly_summary;
alter table if exists public.b2_run_logs rename to naver_report_delivery_logs;

create table if not exists public.naver_works (
  id bigint generated by default as identity primary key,
  work_title text not null unique,
  identifier text,
  rights_holder_name text,
  status text not null default 'Active',
  naver_report_enabled boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.naver_rights_holders (
  id bigint generated by default as identity primary key,
  rights_holder_name text not null unique,
  email text,
  current_work_title text,
  naver_report_enabled boolean not null default true,
  update_cycle text,
  looker_spreadsheet_url text,
  looker_studio_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.naver_clip_report_legacy_rows (
  id bigint generated by default as identity primary key,
  video_url text,
  uploaded_at date,
  channel_name text,
  view_count bigint not null default 0,
  checked_at date not null default current_date,
  clip_title text,
  work_title text,
  platform text,
  rights_holder_name text,
  identifier text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.naver_report_delivery_logs (
  id bigint generated by default as identity primary key,
  run_id text,
  execution_mode text,
  send_notifications boolean not null default false,
  status text not null default 'stub_only',
  result_json jsonb not null default '{}',
  created_at timestamptz not null default now()
);

do $$
begin
  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'naver_works' and column_name = 'content_name'
  ) and not exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'naver_works' and column_name = 'work_title'
  ) then
    alter table public.naver_works rename column content_name to work_title;
  end if;

  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'naver_works' and column_name = 'active_flag'
  ) and not exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'naver_works' and column_name = 'status'
  ) then
    alter table public.naver_works rename column active_flag to status;
  end if;
end;
$$;

alter view if exists public.v_b2_clip_reports_daily_latest rename to v_naver_clip_report_daily_latest;
alter view if exists public.v_b2_clip_reports_daily_history rename to v_naver_clip_report_daily_history;

drop function if exists public.refresh_b2_clip_reports_year(integer);

create or replace function public.refresh_naver_clip_report_year(target_year integer)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  delete from public.naver_clip_report_yearly_summary
  where year = target_year;

  insert into public.naver_clip_report_yearly_summary (
    year,
    rights_holder_name,
    work_title,
    identifier,
    clip_count,
    total_views,
    max_view_count,
    first_checked_at,
    latest_checked_at,
    updated_at
  )
  select
    extract(year from checked_at at time zone 'Asia/Seoul')::integer as year,
    coalesce(rights_holder_name, '') as rights_holder_name,
    coalesce(work_title, '') as work_title,
    coalesce(identifier, '') as identifier,
    count(*) as clip_count,
    sum(view_count) as total_views,
    max(view_count) as max_view_count,
    min(checked_at) as first_checked_at,
    max(checked_at) as latest_checked_at,
    now() as updated_at
  from public.naver_clip_report_daily_rows
  where extract(year from checked_at at time zone 'Asia/Seoul')::integer = target_year
  group by
    extract(year from checked_at at time zone 'Asia/Seoul')::integer,
    coalesce(rights_holder_name, ''),
    coalesce(work_title, ''),
    coalesce(identifier, '');
end;
$$;

create or replace view public.v_naver_clip_report_daily_latest as
select d.*
from public.naver_clip_report_daily_rows d
join (
  select run_id
  from public.naver_clip_report_runs
  where status = 'success'
  order by checked_at desc
  limit 1
) latest on latest.run_id = d.run_id;

create or replace view public.v_naver_clip_report_daily_history as
select
  d.*,
  r.status as run_status,
  r.triggered_by,
  r.finished_at,
  extract(year from d.checked_at at time zone 'Asia/Seoul')::integer as checked_year,
  (d.checked_at at time zone 'Asia/Seoul')::date as checked_date_kst
from public.naver_clip_report_daily_rows d
join public.naver_clip_report_runs r on r.run_id = d.run_id;

alter index if exists public.b2_content_catalog_naver_report_enabled_idx rename to naver_works_report_enabled_idx;
alter index if exists public.b2_clip_report_runs_checked_at_idx rename to naver_clip_report_runs_checked_at_idx;
alter index if exists public.b2_clip_report_runs_status_checked_idx rename to naver_clip_report_runs_status_checked_idx;
alter index if exists public.b2_clip_reports_daily_run_video_uidx rename to naver_clip_report_daily_rows_run_video_uidx;
alter index if exists public.b2_clip_reports_daily_checked_at_idx rename to naver_clip_report_daily_rows_checked_at_idx;
alter index if exists public.b2_clip_reports_daily_holder_checked_idx rename to naver_clip_report_daily_rows_holder_checked_idx;
alter index if exists public.b2_clip_reports_daily_work_checked_idx rename to naver_clip_report_daily_rows_work_checked_idx;
alter index if exists public.b2_clip_reports_daily_identifier_checked_idx rename to naver_clip_report_daily_rows_identifier_checked_idx;
alter index if exists public.b2_clip_reports_year_holder_year_idx rename to naver_clip_report_yearly_summary_holder_year_idx;
alter index if exists public.b2_clip_reports_test_checked_at_idx rename to naver_clip_report_staging_checked_at_idx;
alter index if exists public.b2_clip_reports_test_rights_holder_idx rename to naver_clip_report_staging_rights_holder_idx;
alter index if exists public.b2_clip_reports_test_identifier_idx rename to naver_clip_report_staging_identifier_idx;

alter policy if exists service_role_all_traces
  on public.automation_agent_traces
  rename to service_role_all_automation_agent_traces;

alter policy if exists service_role_all_approvals
  on public.automation_approvals
  rename to service_role_all_automation_approvals;

alter policy if exists service_role_all_invocations
  on public.automation_tool_invocations
  rename to service_role_all_automation_tool_invocations;

commit;
