-- Migration 011: add metabase_embed_url to naver_rights_holders
-- Stores per-rights-holder Metabase public embed URL generated by
-- scripts/create_metabase_b2_dashboard.py

alter table public.naver_rights_holders
  add column if not exists metabase_embed_url text;
