-- Migration 012: seed_channel 스키마 확장 + 테스트 데이터
-- ============================================================

begin;

-- ─────────────────────────────────────────────────────────────
-- 1. seed_channel 신규 컬럼 추가
-- ─────────────────────────────────────────────────────────────
alter table public.seed_channel
  add column if not exists channel_title text,
  add column if not exists managed_by    text,        -- 담당자 ("user" 예약어 회피)
  add column if not exists type          text,        -- 채널 유형 (드라마클립, 영화클립 등)
  add column if not exists status        text not null default 'active';

-- ─────────────────────────────────────────────────────────────
-- 2. kakao_creators 테이블 생성
-- ─────────────────────────────────────────────────────────────
create table if not exists public.kakao_creators (
  id             bigint generated by default as identity primary key,
  creator_name   text    not null,
  kakao_channel  text,                       -- 카카오 채널명 또는 URL
  contact_email  text,
  phone_number   text,
  status         text    not null default 'active'
                   check (status in ('active', 'inactive', 'pending')),
  note           text,
  onboarded_at   timestamptz,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now()
);

-- ─────────────────────────────────────────────────────────────
-- 3. seed_channel 테스트 데이터
-- ─────────────────────────────────────────────────────────────
insert into public.seed_channel
  (channel_title, channel_id, channel_url, managed_by, type, status, platform)
values
  ('드라마클립 TV',        'UCtest_drama001', 'https://www.youtube.com/@dramacliprpa001', '홍길동', '드라마클립', 'active',   'youtube'),
  ('영화명장면 모음',      'UCtest_movie002', 'https://www.youtube.com/@moviescenekr002',  '김철수', '영화클립',   'active',   'youtube'),
  ('국내드라마 하이라이트', 'UCtest_kdrama003','https://www.youtube.com/@kdramahighlight003','이영희', '드라마클립', 'active',   'youtube'),
  ('네이버클립 테스트',    'naver_test001',   'https://clip.naver.com/channel/test001',    '박민지', '드라마클립', 'active',   'naver'),
  ('예능 모음zip',         'UCtest_entmt005', 'https://www.youtube.com/@entrtainmentzip005','최준호', '예능클립',  'inactive', 'youtube')
on conflict (channel_url) do nothing;

-- ─────────────────────────────────────────────────────────────
-- 4. work_requests 테스트 데이터
-- ─────────────────────────────────────────────────────────────
insert into public.work_requests
  (work_title, channel_name, creator_email, status, requested_at, processed_at, drive_link)
values
  ('21세기 대군부인', '유호영', 'creator1@test.com', 'pending',
   now() - interval '2 days',  null, null),
  ('현상수배',       '정호영', 'creator2@test.com', 'approved',
   now() - interval '7 days',  now() - interval '5 days',
   'https://drive.google.com/file/d/1SampleApprovedFileId001'),
  ('사내맞선',       '김태리', 'creator3@test.com', 'approved',
   now() - interval '12 days', now() - interval '10 days',
   'https://drive.google.com/file/d/1SampleApprovedFileId002'),
  ('스물다섯 스물하나', '이수현', 'creator4@test.com', 'rejected',
   now() - interval '9 days',  now() - interval '7 days', null),
  ('빨간 단추',      '최준호', 'creator5@test.com', 'pending',
   now() - interval '1 day',   null, null)
on conflict do nothing;

-- ─────────────────────────────────────────────────────────────
-- 5. kakao_creators 테스트 데이터
-- ─────────────────────────────────────────────────────────────
insert into public.kakao_creators
  (creator_name, kakao_channel, contact_email, phone_number, status, note, onboarded_at)
values
  ('홍길동', '@dramacliprpa_hgd', 'hgd@test.com', '010-1234-5678', 'active',   '드라마 클립 전문 크리에이터', now() - interval '30 days'),
  ('김철수', '@moviescenekr_kcs', 'kcs@test.com', '010-2345-6789', 'active',   '영화 명장면 콘텐츠',         now() - interval '20 days'),
  ('이영희', '@kdrama_lyh',       'lyh@test.com', '010-3456-7890', 'pending',  '온보딩 진행 중',             null),
  ('박민지', '@naverclip_pmj',    'pmj@test.com', '010-4567-8901', 'active',   '네이버 클립 활성',           now() - interval '15 days'),
  ('최준호', '@entzip_cjh',       'cjh@test.com', '010-5678-9012', 'inactive', '활동 중단',                  now() - interval '60 days');

commit;
