"use client";

import { useQuery } from "@tanstack/react-query";
import { fetchAdminChannels } from "@/lib/api";

export default function AdminChannelsPage() {
  const query = useQuery({ queryKey: ["admin-channels"], queryFn: fetchAdminChannels });
  return <div className="p-8"><h1 className="text-2xl font-bold text-slate-950">{"\ucc44\ub110\uc870\ud68c"}</h1><p className="mt-1 text-sm text-slate-500">{"\ub4f1\ub85d\ub41c \ucc44\ub110\uc758 \uc6b4\uc601 \uc0c1\ud0dc\uc640 \uc601\uc0c1 \uc218\ub97c \ud655\uc778\ud569\ub2c8\ub2e4."}</p><div className="mt-6 overflow-hidden rounded-lg border border-slate-200 bg-white">{query.isLoading && <div className="p-8 text-center text-sm text-slate-500">{"\ucc44\ub110\uc744 \ubd88\ub7ec\uc624\ub294 \uc911\uc785\ub2c8\ub2e4."}</div>}{query.isError && <div className="p-8 text-center text-sm text-red-600">{(query.error as Error).message}</div>}{query.data && <table className="w-full min-w-[760px] text-sm"><thead className="bg-slate-50 text-left text-slate-500"><tr><th className="px-5 py-3 font-medium">{"\ucc44\ub110\uba85"}</th><th className="px-5 py-3 font-medium">{"\ud50c\ub7ab\ud3fc"}</th><th className="px-5 py-3 font-medium">{"\ub2f4\ub2f9\uc790"}</th><th className="px-5 py-3 font-medium">{"\ub4f1\ub85d\uc77c"}</th><th className="px-5 py-3 font-medium">{"\uc601\uc0c1 \uc218"}</th><th className="px-5 py-3 font-medium">{"\uc0c1\ud0dc"}</th></tr></thead><tbody className="divide-y divide-slate-100">{query.data.items.map((channel) => <tr key={channel.channel_id} className="hover:bg-slate-50"><td className="px-5 py-4 font-medium text-slate-900">{channel.name}</td><td className="px-5 py-4 text-slate-600">{channel.platform}</td><td className="px-5 py-4 text-slate-600">{channel.owner}</td><td className="px-5 py-4 text-slate-600">{channel.registered_at}</td><td className="px-5 py-4 text-slate-600">{channel.video_count}</td><td className="px-5 py-4"><span className="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-medium text-slate-700">{channel.status}</span></td></tr>)}</tbody></table>}</div></div>;
}
